問題13.1
(1)x try and catch節における処理を例外処理という。
(2)o 要素数3の配列の要素は添字0,1,2でのみ参照できる。
(3)o そのとおりである。
(4)x 他のメソッド内で投げられた例外も受けることができる。
(5)x finallyの間違いである。
(6)o 投げることがある。
(7)o 表示される。
(8)x チェックされない。
(9)o チェックされる。
[プログラムの説明]

[まとめ]

[理解度]

[感想]

[特記事項]
